-- 0033: seed public.category_attributes from Mirakl's required-attribute schema.
--
-- Mirakl's /api/products/attributes lists each (attribute, hierarchy_code,
-- requirement_level). When requirement_level='REQUIRED' for a hierarchy,
-- Mirakl rejects PM01 rows in that hierarchy (or any descendant) that lack
-- the attribute. Our PM01 dispatcher needs this map to know which extra
-- columns to write for each row.
--
-- Reproducibility: this migration hard-codes the 120 (hierarchy, code) pairs
-- pulled from the live Mirakl API on 2026-05-07. Re-running is safe — every
-- INSERT has ON CONFLICT DO UPDATE. If Mirakl adds a new required attribute
-- in the future, regenerate via tools/extract-mirakl-required-attrs.py and
-- create a new migration; do NOT edit this file in place.

DROP TABLE IF EXISTS pg_temp.tmp_mirakl_required;
CREATE TEMP TABLE tmp_mirakl_required (
  hierarchy_code text NOT NULL,
  attribute_code text NOT NULL,
  label_he text,
  type text,
  values_list_code text,
  PRIMARY KEY (hierarchy_code, attribute_code)
) ON COMMIT DROP;

INSERT INTO pg_temp.tmp_mirakl_required VALUES
  ('10161210mp', '6221', 'מתאים לאינדוקציה', 'list', 'boolean-values'),
  ('10161211mp', '6221', 'מתאים לאינדוקציה', 'list', 'boolean-values'),
  ('10161213mp', '6221', 'מתאים לאינדוקציה', 'list', 'boolean-values'),
  ('10161214mp', '6221', 'מתאים לאינדוקציה', 'list', 'boolean-values'),
  ('10161216mp', '6221', 'מתאים לאינדוקציה', 'list', 'boolean-values'),
  ('10161217mp', '6221', 'מתאים לאינדוקציה', 'list', 'boolean-values'),
  ('10161220mp', '6221', 'מתאים לאינדוקציה', 'list', 'boolean-values'),
  ('10161610mp', '2009', 'רמות השחזה', 'list', '2009-2009'),
  ('10170000mp', '2070', 'הרכב הבד', 'text', NULL),
  ('10181318mp', '6221', 'מתאים לאינדוקציה', 'list', 'boolean-values'),
  ('10182010mp', '6221', 'מתאים לאינדוקציה', 'list', 'boolean-values'),
  ('10182012mp', '6221', 'מתאים לאינדוקציה', 'list', 'boolean-values'),
  ('10201500mp', '2070', 'הרכב הבד', 'text', NULL),
  ('10213010mp', '5522', 'רוחב', 'number', NULL),
  ('10213010mp', '6176', 'סוג פתיחה', 'list', '6176-10213010cls'),
  ('10213010mp', '2442', 'מספר דלתות', 'number', NULL),
  ('10213515mp', '2147', 'דרגת קושי', 'list', '2147-10213515cls'),
  ('10213515mp', '2044', 'מידות מזרן', 'list', '2044-10213515cls'),
  ('15161611mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('15161614mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('15162000mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('25121200mp', '2070', 'הרכב הבד', 'text', NULL),
  ('25122200mp', '2070', 'הרכב הבד', 'text', NULL),
  ('25122800mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('25123000mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('25123000mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('25123000mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('25123100mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('25123100mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('25123100mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('25123600mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('25123600mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('25160000mp', '2070', 'הרכב הבד', 'text', NULL),
  ('25171500mp', '2070', 'הרכב הבד', 'text', NULL),
  ('25201200mp', '2070', 'הרכב הבד', 'text', NULL),
  ('30141700mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30142010mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30142011mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30301010mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30301013mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30301014mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30301014mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('30301015mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30301015mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('30301111mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30301210mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('30301213mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30301213mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('30301215mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30301215mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('30301215mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('30301410mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('30301410mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30301500mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('30301711mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('30301800mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30301900mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30302010mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('30302010mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('30302011mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30302110mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30302111mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30302111mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('30302111mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('30302112mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30302112mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('30302112mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('30302710mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('30302711mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('35201200mp', '2070', 'הרכב הבד', 'text', NULL),
  ('35201300mp', '2070', 'הרכב הבד', 'text', NULL),
  ('35211900mp', '2070', 'הרכב הבד', 'text', NULL),
  ('40100000mp', '2070', 'הרכב הבד', 'text', NULL),
  ('40110000mp', '2070', 'הרכב הבד', 'text', NULL),
  ('40120000mp', '2070', 'הרכב הבד', 'text', NULL),
  ('40130000mp', '2070', 'הרכב הבד', 'text', NULL),
  ('50111100mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('55101400mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55101500mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55131100mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55131200mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55131300mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55131400mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55131500mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55131600mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55151300mp', '5589', 'גודל מסך', 'number', NULL),
  ('55151300mp', '6030', 'משקל', 'number', NULL),
  ('55151300mp', '2473', 'מערכת הפעלה', 'list', '2473-55151300cls'),
  ('55151300mp', '2165', 'נפח אחסון', 'list', '2165-55151300cls'),
  ('55151300mp', '2474', 'סוג מעבד', 'list', '2474-55151300cls'),
  ('55151300mp', '2166', 'זיכרון RAM', 'list', '2166-55151300cls'),
  ('55161500mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55161500mp', '2064', 'דירוג המזגן', 'text', NULL),
  ('55161500mp', '2062', 'יצרן המזגן', 'text', NULL),
  ('55161600mp', '2064', 'דירוג המזגן', 'text', NULL),
  ('55161600mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55161600mp', '2062', 'יצרן המזגן', 'text', NULL),
  ('55161700mp', '2062', 'יצרן המזגן', 'text', NULL),
  ('55161700mp', '2064', 'דירוג המזגן', 'text', NULL),
  ('55161700mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55181000mp', '5589', 'גודל מסך', 'number', NULL),
  ('55200000mp', '2054', 'דירוג אנרגטי', 'text', NULL),
  ('55200000mp', '2055', 'תוקף דירוג אנרגטי', 'text', NULL),
  ('55200000mp', '2056', 'נפח תא קירור', 'text', NULL),
  ('70000000mp', '2050', 'סוכר בכמות גבוהה', 'list', 'boolean-values'),
  ('70000000mp', '2051', 'שומן רווי בכמות גבוהה', 'list', 'boolean-values'),
  ('70000000mp', '2049', 'נתרן בכמות גבוהה', 'list', 'boolean-values'),
  ('70000000mp', '6044', 'מכיל אלרגנים', 'text', NULL),
  ('70000000mp', '6043', 'עלול להכיל אלרגנים', 'text', NULL),
  ('70000000mp', '5846', 'ללא גלוטן', 'list', 'boolean-values'),
  ('70230000mp', '9940', 'אחוז אלכוהול', 'text', NULL),
  ('70230000mp', '9941', 'כשר', 'list', 'boolean-values'),
  ('70231014mp', '9937', 'סוג משקה', 'list', '9937-70231014cls'),
  ('75101000mp', '9946', 'סוג מרכב', 'list', '9946-75101000cls'),
  ('75101000mp', '9942', 'סוג מנוע', 'list', '9942-75101000cls'),
  ('75101000mp', '9944', 'סוג הנעה', 'list', '9944-75101000cls'),
  ('75101000mp', '9953', 'רמת אבזור בטיחותי', 'list', '9953-75101000cls'),
  ('75101000mp', '9945', 'תיבת הילוכים', 'list', '9945-75101000cls'),
  ('75101000mp', '9954', 'דרגת זיהום', 'list', '9954-75101000cls'),
  ('75121000mp', '6185', 'קוטר', 'number', NULL);

-- Walk each leaf category's parent chain and copy ancestor required attrs
-- down to the leaf. The PM01 dispatcher only ever queries by leaf, so we
-- fully expand here rather than recursing at runtime.
WITH RECURSIVE chain AS (
  SELECT id AS leaf_id,
         sp_category_code AS curr_code, parent_code AS next_code, 0 AS depth
    FROM public.categories
   WHERE coalesce(is_leaf, false) = true
  UNION ALL
  SELECT chain.leaf_id,
         c.sp_category_code, c.parent_code, chain.depth + 1
    FROM chain
    JOIN public.categories c ON c.sp_category_code = chain.next_code
   WHERE chain.next_code IS NOT NULL AND chain.next_code <> '' AND chain.depth < 6
),
inherited AS (
  SELECT DISTINCT chain.leaf_id, t.attribute_code, t.label_he, t.type, t.values_list_code
    FROM chain
    JOIN pg_temp.tmp_mirakl_required t ON t.hierarchy_code = chain.curr_code
)
INSERT INTO public.category_attributes (category_id, attribute_code, label_he, required, type, value_list)
SELECT i.leaf_id, i.attribute_code, i.label_he, true, i.type,
       CASE WHEN i.values_list_code IS NOT NULL
            THEN jsonb_build_object('list_code', i.values_list_code)
            ELSE NULL END
  FROM inherited i
ON CONFLICT (category_id, attribute_code) DO UPDATE
  SET label_he = EXCLUDED.label_he,
      required = true,
      type = EXCLUDED.type,
      value_list = EXCLUDED.value_list;
